CFG = {
    "master_agreements": {
        "name": "master_agreements",
        "url": "http://purchweb.austintexas.gov/search/RTMATSReport.cfm",
        "primary_key": "DOCUMENT ID",
        "ref_obj": ["object_13"],
        "obj": None,
        "scene": "scene_123",
        "view": "view_397",
        "include_ids": True,
        "form_data": {"selauth": "2400"},
        "fieldnames": [
            "DCD",
            "DDEP",
            "DOCUMENT ID",
            "DOCUMENT DESCRIPTION",
            "ADEP",
            "LN",
            "AUTH AMT",
            "ENC AMT",
            "EXP AMT",
            "REM ENC AMT",
            "REM AUTH AMT",
            "NO LMT FL",
            "ACTIVE?",
            "EXCL / INCL",
            "AUTH SHARE PCT",
            "ORD SHARE PCT",
            "AUTH AMT",
            "ENC AMT",
            "EXP AMT",
            "BAL AMT",
            "PCT AMT",
            "PCT TIME",
            "FLAG",
            "BUYER",
            "REQUESTOR",
            "VEND-CNT",
            "VENDOR CODE",
            "VENDOR NAME",
            "BEGIN DATE",
            "EXPIR DATE",
            "OPT-CNT",
            "LEN",
            "UNIT",
            "RPT-1",
            "GO CAT",
            "Contract Display",
        ],
    },
    "objects": {
        "name": "objects",
        "url": "http://finance.austintexas.gov/web/controller/afs3/acctlookup/ObjectLookupAction.cfm",
        "primary_key": "Code",
        "ref_obj": ["object_6"],
        "obj": None,
        "scene": "scene_123",
        "view": "view_398",
        "include_ids": True,
        "form_data": {"ObjectName": ""},
        "fieldnames": ["Code", "Name"],
    },
    "units": {
        "name": "units",
        "url": "http://finance.austintexas.gov/web/controller/afs3/acctlookup/UnitLookupAction.cfm",
        "primary_key": "Unit",
        "ref_obj": ["object_7"],
        "obj": None,
        "scene": "scene_123",
        "view": "view_399",
        "include_ids": True,
        "form_data": {"DeptNumber": "2400", "UnitName": ""},
        "fieldnames": ["Dept", "Unit", "Name", "Active"],
    },
}
